### PR TITLE
UP - Uploading Humanitarian Model

### PR DESCRIPTION
**Pull request by vaap1997**
Hey Arnaud, it is a humanitarian model of path finding from schools to hospitals. This is a result of a fuzzy model to assign hospital to schools considering vulnerability index. There is a missing file that should be on the  folder "data". The name of the file is "clean_vias" and it is in this link: https://drive.google.com/drive/folders/1qhcx_m2fuyMLlqjDZ576impnCdDbZjpn?usp=sharing  

Tell me if you got any issues, we are working now on ram consumption.

### CODE REVIEW

**Comment by agrignard** [comment]
What do you mean by this is  "humanitarian model of path finding from schools to hospitals" did you start a new project? If yes did you keep the backward compatibility with the original lego reader?

**Comment by agrignard** [comment]
@vaap1997 did you push the source file? I cannot find the folder corresponding to the Humanitarian project described here
https://github.com/CityScope/CSL_Lima/wiki/HumanitarianModel

**Comment by vaap1997** [comment]
@agrignard Done! We put it on dropbox so people don't need to ask for access. Thanks!

**Comment by agrignard** [comment]
ok but what about the source code?

HumanitarianModel.pde

Don't you want to push it in the wiki?

**Comment by vaap1997** [comment]
I did push it but I can't see it and I can't see the UP branch either. I can push it again. Should I created again the UP branch or just push it on the master? (I saw you delete UP branch, maybe it wasn't on purpose)

**Comment by agrignard** [comment]
Yes I don't knwo exactly what went wrong here, yes you can just push it in the master

**Pull request merged**
